Algoritmo "LÓGICA DE PROGRAMAÇÃO - ATIVIDADE 24"
Var

REAIS, DOLAR, MARCO, LIBRA : REAL

Inicio

Escreval ("FAÇA SUA CONVERSÃO DE REAIS PARA OUTRAS MOEDAS")
Escreval ("PRIMEIRO, ME INFORME QUAL VALOR GOSTARIA DE CONVERTER?")
Leia (reais)
dolar <- reais /1.8
Escreval ("VOCE POSSUI: ", dolar ," DE DOLARES")
marco <- reais / 2
Escreval ("VOCE POSSUI: ", MARCO ," DE MARCO ALEMÃO")
libra <- reais / 3.57
Escreval ("VOCE POSSUI: ", libra ," DE LIBRA ESTERLINA.")
 
Fimalgoritmo